name: Trigger auto deployment for cindy3

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cindy3-AutoDeployTrigger-20ed3b66-397d-4749-82c4-e72a0fa621fa.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CINDY3_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cindy.azurecr.io
          registryUsername: ${{ secrets.CINDY3_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CINDY3_REGISTRY_PASSWORD }}
          containerAppName: cindy3
          resourceGroup: cindy11
          imageToBuild: cindy.azurecr.io/acr-build-helloworld-node-master:${{ github.sha }}
          dockerfilePath: Dockerfile

     

